### ISSUE TITLE
Publish CirrusMDSDK spec to CocoaPods trunk

### ISSUE THREAD

**Issue by phatblat** [CirrusMD/CirrusMD-iOS-SDK-Example#9]
I see in your [readme](https://github.com/CirrusMD/CirrusMD-iOS-SDK-Example#cocoapods) that this pod is published to your private (yet publicly available) spec repo at `https://github.com/CirrusMD/podspecs.git`. It would be easier for devs to discover and install this pod if it were published to [CocoaPods trunk](https://guides.cocoapods.org/making/getting-setup-with-trunk.html). Is there a reason you're not publishing to trunk?

**Comment by steam** [comment]
Sorry for the (very) delayed response, @phatblat. We considered publishing to CocoaPods trunk but decided against it. While publicly available in the example application, the CirrusMDSDK isn't truly public. Using the SDK in any meaningful way requires a relationship with CirrusMD and we feel that having it publicly searchable on Cocoapods.org might cause confusion.

**Comment by phatblat** [comment]
Wouldn't you want your SDK and service to be more discoverable? [Crashlytics](https://cocoapods.org/pods/Crashlytics) is an example of a private vendored pod which requires an account and API key to use. I realize their service only requires a free account, but perhaps something you could mention to your business/marketing partners.
